[package]
name = "web-surface"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
url = "2"
time = { workspace = true }
base64 = { workspace = true }
murmur3 = { workspace = true }
