[package]
name = "port-scan"
version = "0.1.0"
edition = "2021"

[dependencies]
toolbox-core = { path = "../../core" }
anyhow = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }
