name: bench
on:
  workflow_dispatch:
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Start services
        run: docker compose -f ops/bench/docker-compose.yml up -d
      - name: Run bench
        run: cargo run -p toolbox -- bench --out target/bench --qps 600 --store
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bench-artifacts
          path: |
            target/bench/*.jsonl
            target/bench/*.parquet
            target/bench/results.db

